apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grapple-solution-framework-components
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '70'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: registry/<CLUSTER_NAME>/components/grapple-solution-framework
    # path: <REGISTRY_PATH>/components/grapple-solution-framework
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: grpl-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
